# Qust

支持流式计算的查询引擎，底层基于rust, 应用层用的python
------
* 流式计算，算子有状态保留，支持流式计算
* 性能高，大多数情况下速度比polars高，内存消耗更少
* 算子丰富，内置丰富的金融算子，比如k线合成、回测、组合优化等等
* 可拓展性强，底层基于rust的`datafusion`, 拓展到分布式很方便.

[文档地址](https://raw.githack.com/baiguoname/qust/main/examples/docs/qust.html)

[git地址](https://github.com/baiguoname/qust)

[demo地址](https://github.com/baiguoname/qust/blob/main/examples/demo.ipynb)

# 安装

```python
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple qust
```
(只支持windows和linux)

# 目的

量化框架的不可能三角：

1. 高性能

2. 易用

3. 实盘回测一致

比如一些事件驱动的框架，优点是实盘回测一致，缺点是速度很慢， 而且不易用，毕竟操作 `DataFrame` 更加直观

还有一些向量化回测的框架, 优点是回测性能好，但是实盘回测不一致，而且从回测阶段转到实盘阶段比较麻烦

另外就是实盘和回测两套代码这种框架，这个不易用

总结下来就是，要想易用，就得用 `DataFrame` api 去做策略，要想实盘回测一致，就得用事件驱动

有没有方法能同时兼顾两者？有，用流式计算

底层用rust写就能实现高性能，api 封装成python的 `DataFrame` api 就能实现易用性，流式计算本身就是事件驱动，实盘回测就一致。qust的目的就是实现这个

# 使用

In [26]:
import qust as qs
from qust import (col, pms)
import polars as pl
import numpy as np

In [27]:
n = 10
data = pl.DataFrame({
    "factor": np.random.randn(n),
    "code": np.random.choice(["a", "b", "c"], size=n, replace=True),
})
data_next = pl.DataFrame({
    "factor": np.random.randn(n),
    "code": np.random.choice(["a", "b", "c"], size=n, replace=True),
})

df = qs.with_cols(
    col("factor").mean().expanding().alias("cum_mean"),
    col("factor").mean().rolling(3).alias("rolling_mean"),
    col("factor").mean().expanding().over("code").alias("cum_mean_over")
)

In [28]:
print(df.calc_data(data))

shape: (10, 5)
┌───────────┬──────┬───────────┬──────────────┬───────────────┐
│ factor    ┆ code ┆ cum_mean  ┆ rolling_mean ┆ cum_mean_over │
│ ---       ┆ ---  ┆ ---       ┆ ---          ┆ ---           │
│ f64       ┆ str  ┆ f64       ┆ f64          ┆ f64           │
╞═══════════╪══════╪═══════════╪══════════════╪═══════════════╡
│ -1.664883 ┆ b    ┆ -1.664883 ┆ null         ┆ -1.664883     │
│ -0.187855 ┆ a    ┆ -0.926369 ┆ null         ┆ -0.187855     │
│ -1.11352  ┆ b    ┆ -0.988753 ┆ -0.988753    ┆ -1.389201     │
│ -1.212976 ┆ a    ┆ -1.044808 ┆ -0.838117    ┆ -0.700416     │
│ 1.305776  ┆ b    ┆ -0.574692 ┆ -0.34024     ┆ -0.490876     │
│ -0.418283 ┆ a    ┆ -0.548624 ┆ -0.108494    ┆ -0.606371     │
│ -0.521383 ┆ b    ┆ -0.544732 ┆ 0.122036     ┆ -0.498503     │
│ -2.068707 ┆ c    ┆ -0.735229 ┆ -1.002791    ┆ -2.068707     │
│ -0.46641  ┆ a    ┆ -0.70536  ┆ -1.018833    ┆ -0.571381     │
│ 1.223008  ┆ b    ┆ -0.512523 ┆ -0.437369    ┆ -0.1542       │
└───────────┴──────┴───────────┴──────────────┴───────────────┘

In [29]:
print(df.calc_data(data_next)) # df 里面的算子都状态保留

shape: (10, 5)
┌───────────┬──────┬───────────┬──────────────┬───────────────┐
│ factor    ┆ code ┆ cum_mean  ┆ rolling_mean ┆ cum_mean_over │
│ ---       ┆ ---  ┆ ---       ┆ ---          ┆ ---           │
│ f64       ┆ str  ┆ f64       ┆ f64          ┆ f64           │
╞═══════════╪══════╪═══════════╪══════════════╪═══════════════╡
│ 1.040219  ┆ c    ┆ -0.371365 ┆ 0.598939     ┆ -0.514244     │
│ -2.149415 ┆ c    ┆ -0.519536 ┆ 0.037937     ┆ -1.059301     │
│ -1.031419 ┆ b    ┆ -0.558911 ┆ -0.713538    ┆ -0.300403     │
│ 2.890776  ┆ c    ┆ -0.312505 ┆ -0.096686    ┆ -0.071782     │
│ -0.710796 ┆ c    ┆ -0.339058 ┆ 0.382854     ┆ -0.199585     │
│ -1.043864 ┆ a    ┆ -0.383108 ┆ 0.378705     ┆ -0.665878     │
│ -0.784278 ┆ c    ┆ -0.406706 ┆ -0.846313    ┆ -0.297034     │
│ -0.492146 ┆ c    ┆ -0.411453 ┆ -0.773429    ┆ -0.324907     │
│ 1.290463  ┆ a    ┆ -0.321879 ┆ 0.00468      ┆ -0.339821     │
│ -0.01888  ┆ c    ┆ -0.306729 ┆ 0.259812     ┆ -0.286653     │
└───────────┴──────┴───────────┴──────────────┴───────────────┘

# 与polars语法比较

In [30]:
data = pl.DataFrame({
    "price": range(5),
    "code": ["a", "a", "a", "b", "b"]
})
df = qs.with_cols(
    col("price").sum().expanding().alias("cum_sum_otters"),
    pl.col("price").cum_sum().alias("cum_sum_polars"),
    col("price").sum().expanding().over("code").alias("cum_sum_otters_over"),
    pl.col("price").cum_sum().over("code").alias("cum_sum_polars_over")
)
df.calc_data(data)

shape: (5, 6)
┌───────┬──────┬────────────────┬────────────────┬─────────────────────┬─────────────────────┐
│ price ┆ code ┆ cum_sum_otters ┆ cum_sum_polars ┆ cum_sum_otters_over ┆ cum_sum_polars_over │
│ ---   ┆ ---  ┆ ---            ┆ ---            ┆ ---                 ┆ ---                 │
│ i64   ┆ str  ┆ i64            ┆ i64            ┆ i64                 ┆ i64                 │
╞═══════╪══════╪════════════════╪════════════════╪═════════════════════╪═════════════════════╡
│ 0     ┆ a    ┆ 0              ┆ 0              ┆ 0                   ┆ 0                   │
│ 1     ┆ a    ┆ 1              ┆ 1              ┆ 1                   ┆ 1                   │
│ 2     ┆ a    ┆ 3              ┆ 3              ┆ 3                   ┆ 3                   │
│ 3     ┆ b    ┆ 6              ┆ 6              ┆ 3                   ┆ 3                   │
│ 4     ┆ b    ┆ 10             ┆ 10             ┆ 7                   ┆ 7                   │
└───────┴──────┴────────────────┴────────────────┴─────────────────────┴─────────────────────┘

# 与polars性能比较

In [31]:
import time
n = 2000000
data = pl.DataFrame({
    "factor": np.random.randn(n),
    "code": np.random.choice(["a", "b"], size=n, replace=True),
})

### 1. qust单线程 vs polars多线程

In [32]:
s = time.time()
_ = qs.select(
    col("factor").rank().rolling(10).over("code")
).calc_data(data)
print(f"qust: {(time.time() - s) * 1000.0}.ms")

s = time.time()
_ = data.select(
    pl.col("factor").rolling_rank(10).over("code")
)
print(f"polars: {(time.time() - s) * 1000.0}.ms")

qust: 104.89392280578613.ms
polars: 194.35358047485352.ms

### 2. qust多线程 vs polars多线程

In [33]:
s = time.time()
_ = qs.select(
    col(*[col("factor").mean().alias(f"mean_{i}") for i in range(50)]).rolling(10).over("code")
).calc_data(data)
print(f"qust: {(time.time() - s) * 1000.0}.ms")

s = time.time()
_ = data.select(
    [pl.col("factor").rolling_mean(10).over("code").alias(f"mean_{i}") for i in range(50)]
)
print(f"polars: {(time.time() - s) * 1000.0}.ms")

qust: 137.73751258850098.ms
polars: 382.92813301086426.ms

### 3. qust自定义算子 vs polars自定义算子

In [34]:
class MeanUdf(qs.UdfRow):

    def __init__(self):
        self.sum = 0.0
        self.count = 0.0

    def output_schema(self, input_schema):
        return [("mean_res", pl.Float64)]
    
    def update(self, value):
        self.sum += value
        self.count += 1.0

    def calc(self):
        return [self.sum / self.count]

    def retract(self, value):
        self.sum -= value
        self.count -= 1.0

s = time.time()
_ = qs.select(
    col("factor").udf.row(MeanUdf()).rolling(10).over("code")
).calc_data(data)
print(f"qust: {(time.time() - s)}.s")

s = time.time()
_ = data.select(
    pl.col("factor").rolling_map(lambda x: x.mean(), 10).over("code")
)
print(f"polars: {(time.time() - s)}.s")

qust: 1.3382771015167236.s
polars: 51.07790398597717.s

>--------
| 算子 | qust | polars | 提速 |
|----|------|-------------|---|
| 单个算子 | 100ms | 157ms | 1.5倍 |
| 多个算子 | 110ms | 290ms | 2.5倍 |
| 自定义rolling算子 | 1.5s | 53s | 40倍 |

# 和polars相互使用

In [35]:
data = pl.DataFrame({
    "value": [1, 2, 3, 4, 5]
})
data_next = pl.DataFrame({
    "value": [3, 1, 10]
})

### 1. 在qust里面使用polars

In [36]:
qs.with_cols(
    (pl.col("value") + 1).alias("value+1"),
    (col("value").pl + 2).alias("value+2"),
    col("value").mean().expanding().select(pl.col("value") - 1).alias("value-1")

).calc_data(data)

shape: (5, 4)
┌───────┬─────────┬─────────┬─────────┐
│ value ┆ value+1 ┆ value+2 ┆ value-1 │
│ ---   ┆ ---     ┆ ---     ┆ ---     │
│ i64   ┆ i64     ┆ i64     ┆ f64     │
╞═══════╪═════════╪═════════╪═════════╡
│ 1     ┆ 2       ┆ 3       ┆ 0.0     │
│ 2     ┆ 3       ┆ 4       ┆ 0.5     │
│ 3     ┆ 4       ┆ 5       ┆ 1.0     │
│ 4     ┆ 5       ┆ 6       ┆ 1.5     │
│ 5     ┆ 6       ┆ 7       ┆ 2.0     │
└───────┴─────────┴─────────┴─────────┘

### 2. 在polars里面使用qust

In [37]:
data.select(
    col("value").mean().rolling(3).alias("value_mean1").pl,
    col("value").pl.rolling_mean(3).alias("value_mean2"),
)

shape: (5, 2)
┌───────┬─────────────┐
│ value ┆ value_mean2 │
│ ---   ┆ ---         │
│ f64   ┆ f64         │
╞═══════╪═════════════╡
│ null  ┆ null        │
│ null  ┆ null        │
│ 2.0   ┆ 2.0         │
│ 3.0   ┆ 3.0         │
│ 4.0   ┆ 4.0         │
└───────┴─────────────┘

In [38]:
# 上面的写法没有状态保留, 如果需要状态保留，需要把算子的状态保存到全局变量，使用 `expr.cache(id)`
e = col(
    col("value").mean().alias("mean"),
    col("value").sum().alias("sum"),
).rolling(3)
e_pl = e.cache("unique_id").pl
# 注意这里不能接polars的over，e.cache("unique_id").pl.over("code"), 这种写法会直接报错，
# 可以写成 e.over("code").cache("unique_id").pl, 或者用 data.qs.df
data.select(e_pl)

shape: (5, 1)
┌─────────────┐
│ value       │
│ ---         │
│ struct[2]   │
╞═════════════╡
│ {null,null} │
│ {null,null} │
│ {2.0,6}     │
│ {3.0,9}     │
│ {4.0,12}    │
└─────────────┘

In [39]:
data_next.select(e_pl)

shape: (3, 1)
┌───────────────┐
│ value         │
│ ---           │
│ struct[2]     │
╞═══════════════╡
│ {4.0,12}      │
│ {3.0,9}       │
│ {4.666667,14} │
└───────────────┘

保存到全局的算子状态一直在内存里面，需要清除用:

In [40]:
qs.clear_cache("unique_id") # 单个清除
qs.clear_cache() # 全部清除

由于polars的限制，上面的算子无法多列返回, 所以如果有多列返回，返回的是多列组成的struct

如果需要多列返回，只能这样写:

In [41]:
data.qs.select(e)

shape: (5, 2)
┌──────┬──────┐
│ mean ┆ sum  │
│ ---  ┆ ---  │
│ f64  ┆ i64  │
╞══════╪══════╡
│ null ┆ null │
│ null ┆ null │
│ 2.0  ┆ 6    │
│ 3.0  ┆ 9    │
│ 4.0  ┆ 12   │
└──────┴──────┘

In [42]:
df = qs.select(e)
data.qs.df(df)

shape: (5, 2)
┌──────┬──────┐
│ mean ┆ sum  │
│ ---  ┆ ---  │
│ f64  ┆ i64  │
╞══════╪══════╡
│ null ┆ null │
│ null ┆ null │
│ 2.0  ┆ 6    │
│ 3.0  ┆ 9    │
│ 4.0  ┆ 12   │
└──────┴──────┘

In [43]:
data_next.qs.df(df)

shape: (3, 2)
┌──────────┬─────┐
│ mean     ┆ sum │
│ ---      ┆ --- │
│ f64      ┆ i64 │
╞══════════╪═════╡
│ 4.0      ┆ 12  │
│ 3.0      ┆ 9   │
│ 4.666667 ┆ 14  │
└──────────┴─────┘

# 为什么有polars，还要写qust？

### 1. 流式计算

写量化策略的时候，一般有下面两种方法

1. 向量化计算

2. 事件驱动

如果策略用向量化计算，在实盘的时候就很慢，因为要重复计算历史数据, 而且很多策略没法向量化

如果策略用的事件驱动，回测的时候就很慢，而且事件驱动写法特别麻烦

流计算就是把算子都写成事件驱动的形式。比如计算移动平均，在算子里面存储两个状态 `(sum, count)`, 每有一个行新数据`value`过来，更新算子的内部状态:

`sum = sum + value`

`count = count + 1`

在需要计算结果的时候就用  `sum / count`

```python
data = pl.DataFrame({
    "value": [1, 2, 3, 4, 5]
})
data_next = pl.DataFrame({
    "value": [6, 7, 8]
})

df = qs.with_cols(
    col("value").mean().rolling(3).alias("rolling_mean"),
    col("value").std().expanding().alias("cum_std"),
)

print(df.calc_data(data))
shape: (5, 3)
┌───────┬──────────────┬──────────┐
│ value ┆ rolling_mean ┆ cum_std  │
│ ---   ┆ ---          ┆ ---      │
│ i64   ┆ f64          ┆ f64      │
╞═══════╪══════════════╪══════════╡
│ 1     ┆ null         ┆ null     │
│ 2     ┆ null         ┆ 0.707107 │
│ 3     ┆ 2.0          ┆ 1.0      │
│ 4     ┆ 3.0          ┆ 1.290994 │
│ 5     ┆ 4.0          ┆ 1.581139 │
└───────┴──────────────┴──────────┘
print(df.calc_data(data_next))
shape: (3, 3)
┌───────┬──────────────┬──────────┐
│ value ┆ rolling_mean ┆ cum_std  │
│ ---   ┆ ---          ┆ ---      │
│ i64   ┆ f64          ┆ f64      │
╞═══════╪══════════════╪══════════╡
│ 6     ┆ 5.0          ┆ 1.870829 │
│ 7     ┆ 6.0          ┆ 2.160247 │
│ 8     ┆ 7.0          ┆ 2.44949  │
└───────┴──────────────┴──────────┘
```
在第一个调用`df.calc_data(data)`的时候，df内部的算子都有状态保留，所以在第二个调用`df.calc_data(data_next)`时候，没有重新计算

实际情况是，绝大多数算子都有对应的事件驱动形式，少量的算子比如`pl.col("a").rank()`, 看起来不是事件驱动的形式（当前行的值受到未来行的值的影响），但是其实也可以变换成事件驱动形式，
* 转换成行算子，比如 a 列有a1，a2，a3三个元素，就是`col(a1, a2, a3).rank(axis=1)` 

* 事件驱动形式的批算子，每次计算的时候保证传入的数据完整，比如计算`pl.col("a").rank().over("date")`, 保证每次计算传入的数据包含整天的所有数据

`polars`不是也支持streaming吗？我看了polars的底层，觉得polars的streaming不是真正意义上的流式计算，只是为了避免out of memory，而且局限性大(比如`over`是用的 切割 -> 计算 -> 拼接)。如果polars要实现真正的流式计算，我估计底层得推倒重来改成`datafusion`的那种框架

### 2. 表达式解耦

`polars`的`Expr`用的`enum`, 这样就导致每实现一个算子，底层很多代码都要改, 这样就不难理解为什么一个简单的`pl.col("a").rolling_rank(10)`算子直到最近才实现，而且速度比我一个简单的实现慢一倍。

`datafusion`聚合算子用的`Box<dyn trait>`, 然后根据上下文选择不同路径的`ExecutionPlan`, 这样添加算子很方便，而且优化路径也很清晰，性能还不受影响。

`polars`这种写法还有个缺点，就是导致同样的逻辑写法割裂，比如求和逻辑有下面写法:
* `pl.col("a").sum()`

* `pl.col("a").cum_sum()`

* `pl.col("a").rolling_sum(10)`

* `df.group_by("b").agg([pl.col("a").sum()])`

如果说 `sum()` 和 `rolling_sum(10)`, 都是求和逻辑, 前一个是针对整列，后一个是针对滚动，但是 `rank()`和`rolling_rank(10)`, 又是两个不想关的算子, 而且并不存在`cum_rank()`这个算子，这样逻辑就很割裂，为什么能存在`cum_sum`, 但是不能存在`cum_rank`, `cum_skew`, `cum_cov`? 

相反用`datafusion`的上下文逻辑，写法就比较一致:
* `col("a").sum()`

* `col("a").sum().expanding()`

* `col("a").sum().rolling(10)`

* `col("a").sum().group_by("b")`

### 3. 多列返回

`polars` 和 `datafusion` 对单个算子都不支持多列返回，但是`datafusion`提供了插件接口，能改成多列返回:
```python
n = 7
data = pl.DataFrame({
    "y": np.random.randn(n),
    "x1": np.random.randn(n),
    "x2": np.random.randn(n),
})
res = qs.with_cols(
    col("y", "x1", "x2").stock.ols().rolling(4).add_suffix("rolling_beta"),
).calc_data(data)
print(res)
shape: (7, 5)
┌───────────┬───────────┬───────────┬─────────────────┬─────────────────┐
│ y         ┆ x1        ┆ x2        ┆ x1_rolling_beta ┆ x2_rolling_beta │
│ ---       ┆ ---       ┆ ---       ┆ ---             ┆ ---             │
│ f64       ┆ f64       ┆ f64       ┆ f64             ┆ f64             │
╞═══════════╪═══════════╪═══════════╪═════════════════╪═════════════════╡
│ 0.522261  ┆ -0.376497 ┆ -0.594123 ┆ null            ┆ null            │
│ 1.325991  ┆ -0.723979 ┆ 2.626444  ┆ null            ┆ null            │
│ 1.502309  ┆ -2.089571 ┆ 0.28167   ┆ null            ┆ null            │
│ -0.322316 ┆ 0.00877   ┆ -0.213895 ┆ -0.731707       ┆ 0.271784        │
│ -0.733964 ┆ -0.750248 ┆ -0.592936 ┆ -0.47639        ┆ 0.465733        │
│ 0.445435  ┆ -0.559213 ┆ -0.44069  ┆ -0.56446        ┆ 1.174467        │
│ 1.735427  ┆ -2.403888 ┆ 1.207053  ┆ -0.29973        ┆ 0.849167        │
└───────────┴───────────┴───────────┴─────────────────┴─────────────────┘
```
多列返回我能想到以下好处
* 多列返回在用一些比如k线合成算子，策略信号算子之类的比较方便

* 另一个是避免用`struct`, 如果底层依赖从`arror-rs`改成[`MinArrow`](https://github.com/pbower/minarrow), 估计内存占用能到原来的一半，并且耗时减少

### 4. `datafusion` 功能更齐全，比如:
* 支持`DataFrame` Api 和 sql相互转换，`polars`不行

* 原生支持`arrow`, `datafusion`是`arrow`的一部分，未来生态会更丰富, `polars`自己写了一个`polars-arrow`, 生态割裂

* `datafusion` 有成熟的分布式应用，而且全部开源，`polars` 前期是基于`datafusion`的二次开发，目前分布式刚起步，而且闭源，貌似已经**把主要精力放在商业闭源上面去了**

>--------
`qust`是用`rust`写的一个`datafusion`插件，主要目的是尝试用`DataFrame api`去写事件驱动量化策略，并且保持向量化计算的高性能.

所以主要是添加一些能够状态保留的算子，其他一些无需状态保留的算子，还是依赖于`polars`的算子，比如:
```python
col("a") + 1
```
会报错:
```
TypeError: unsupported operand type(s) for +: 'Expr' and 'int'
```
只能用`polars`的算子:
```python
qs.select(
    pl.col("a") + 1,
    pl.col("a").rank().over("code")
    col("a").select(pl.col("a") + 1).over("code")
)
```

当然，上面说的只是我个人的理解，对这方面有兴趣的朋友可以加我微信交流，微信号: aruster

# 写策略

In [44]:
# 从github读取tick数据
data_kline = pl.read_parquet("https://github.com/baiguoname/qust/blob/main/examples/data/300_1min_vnpy.parquet?raw=true") # 从github读取数据，速度较慢
# 假设历史数据
data_his = data_kline[:600000]
# 假设实盘数据流
data_live = [data_kline[600000:601000], data_kline[601000:602000]]

# 从github读取kine数据
data_tick = pl.read_parquet("https://github.com/baiguoname/qust/blob/main/examples/data/data_tick.parquet?raw=true")

### 1. 有k线数据，实现一个双均线策略

In [45]:
# 策略逻辑
stra = (
    col(
        col("close"),
        col("datetime"),
        col("close").stra.two_ma(10, 20), # 通过算子生成信号
    )
        .with_cols(col("cross_up", "cross_down").stra.to_hold_always().alias("hold")) # 通过信号生成目标持仓
)
# 回测
df_bt = qs.select(
    stra.with_cols(
        col("close", "hold").bt.price()
    ).expanding().select(
        col("datetime", "pnl").fp.group_pnl()
    )
)

# 实盘
df_live = qs.select(stra.expanding().select("hold").last_value())

In [46]:
%%time
# 回测
df_bt.calc_data(data_his)

CPU times: user 37.2 ms, sys: 37 ms, total: 74.2 ms
Wall time: 49.3 ms

shape: (2_500, 3)
┌────────────┬────────┬──────────┐
│ date       ┆ pnl    ┆ pnl_cum  │
│ ---        ┆ ---    ┆ ---      │
│ date       ┆ f64    ┆ f64      │
╞════════════╪════════╪══════════╡
│ 2009-01-05 ┆ 22.14  ┆ 22.14    │
│ 2009-01-06 ┆ -2.74  ┆ 19.4     │
│ 2009-01-07 ┆ 20.98  ┆ 40.38    │
│ 2009-01-08 ┆ 39.31  ┆ 79.69    │
│ 2009-01-09 ┆ -2.92  ┆ 76.77    │
│ …          ┆ …      ┆ …        │
│ 2019-04-11 ┆ 28.23  ┆ -2400.2  │
│ 2019-04-12 ┆ -32.8  ┆ -2433.0  │
│ 2019-04-15 ┆ 26.66  ┆ -2406.34 │
│ 2019-04-16 ┆ 16.95  ┆ -2389.39 │
│ 2019-04-17 ┆ -90.43 ┆ -2479.82 │
└────────────┴────────┴──────────┘

In [47]:
# 实盘
import time
df_live.calc_data(data_his)
for data_live_ in data_live: # 模拟实盘数据流, 实际中应该用异步
    print(f"----接收到实盘数据, 实时数据长度: {data_live_.shape[0]}，开始一轮计算---")
    s = time.time()
    print(df_live.calc_data(data_live_))
    print(f"计算完成, 耗时: {time.time() - s}")
    print("------------------")
# 可以看到虽然历史数据需要几十万，但是每次实盘计算的时间很短，因为是流式计算

----接收到实盘数据, 实时数据长度: 1000，开始一轮计算---
shape: (1, 1)
┌──────┐
│ hold │
│ ---  │
│ f64  │
╞══════╡
│ 1.0  │
└──────┘
计算完成, 耗时: 0.002280712127685547
------------------
----接收到实盘数据, 实时数据长度: 1000，开始一轮计算---
shape: (1, 1)
┌──────┐
│ hold │
│ ---  │
│ f64  │
╞══════╡
│ 1.0  │
└──────┘
计算完成, 耗时: 0.001985788345336914
------------------

### 2. 有数据源，这个数据源不断获取多个品种的tick数据，策略需要分品种将数据不断合成1min k线，并且生成双均线的开仓逻辑，然后用0.01止损作为出场

In [48]:
# 策略逻辑
col_tick = col("t", "c", "v", "bid1", "ask1", "bid1_v", "ask1_v")
stra = (
    col(
        col("c"),
        col("t"),
        col_tick.kline.future_ra1m.with_cols(
            col("close").stra.two_ma(10, 20).filter_cb("is_finished")
        ),
    ).with_cols(
        col(
            col("cross_up", "c").stra.exit_by_pct(0.01, False).alias("take_profit_long"),
            col("cross_up", "c").stra.exit_by_pct(0.01, True).alias("stop_loss_long"),
        )
            .with_cols(
                (pl.col("take_profit_long") | pl.col("stop_loss_long")).alias("exit_long_sig") 
            ),
        col(
            col("cross_down", "c").stra.exit_by_pct(0.01, True).alias("take_profit_short"),
            col("cross_down", "c").stra.exit_by_pct(0.01, False).alias("stop_loss_short"),
        )   
            .with_cols(
                (pl.col("take_profit_short") | pl.col("stop_loss_short")).alias("exit_short_sig")
            )
    ).with_cols(
        col("cross_up", "exit_long_sig", "cross_down", "exit_short_sig")
            .stra
            .to_hold_two_sides()
            .alias("hold")
    )
)

# 价格回测
df_bt_price = (qs
    .select(
        stra
            .with_cols(col("c", "hold").bt.price())
            .expanding()
            .over("ticker")
            .select(col("t", "pnl").fp.group_pnl())
    )
)

# tick回测
df_bt_tick = (qs.select(
    col(
        "bid1",
        "ask1",
        stra,
    )
        .with_cols(
            col("hold", "c", "bid1", "ask1")
                .bt
                .tick(qs.TradePriceType.queue, qs.MatchPriceType.simnow)
                # .tick(qs.TradePriceType.last_price, qs.MatchPriceType.void)
        )
        .expanding()
        .over("ticker")
        .select(col("t", "pnl").fp.group_pnl())
    )
)

In [49]:
df_bt_price.calc_data(data_tick)

shape: (23, 3)
┌────────────┬───────┬─────────┐
│ date       ┆ pnl   ┆ pnl_cum │
│ ---        ┆ ---   ┆ ---     │
│ date       ┆ f64   ┆ f64     │
╞════════════╪═══════╪═════════╡
│ 2024-01-06 ┆ 11.0  ┆ 11.0    │
│ 2024-01-08 ┆ 34.0  ┆ 45.0    │
│ 2024-01-09 ┆ 68.0  ┆ 113.0   │
│ 2024-01-10 ┆ -8.0  ┆ 105.0   │
│ 2024-01-11 ┆ 169.0 ┆ 274.0   │
│ …          ┆ …     ┆ …       │
│ 2024-01-27 ┆ 4.0   ┆ 515.0   │
│ 2024-01-29 ┆ -69.0 ┆ 446.0   │
│ 2024-01-30 ┆ -21.0 ┆ 425.0   │
│ 2024-01-31 ┆ 7.0   ┆ 432.0   │
│ 2024-02-01 ┆ -63.0 ┆ 369.0   │
└────────────┴───────┴─────────┘

In [50]:
df_bt_tick.calc_data(data_tick)

shape: (23, 3)
┌────────────┬────────┬─────────┐
│ date       ┆ pnl    ┆ pnl_cum │
│ ---        ┆ ---    ┆ ---     │
│ date       ┆ f64    ┆ f64     │
╞════════════╪════════╪═════════╡
│ 2024-01-06 ┆ 0.0    ┆ 0.0     │
│ 2024-01-08 ┆ 0.0    ┆ 0.0     │
│ 2024-01-09 ┆ 116.0  ┆ 116.0   │
│ 2024-01-10 ┆ 0.0    ┆ 116.0   │
│ 2024-01-11 ┆ 0.0    ┆ 116.0   │
│ …          ┆ …      ┆ …       │
│ 2024-01-27 ┆ 0.0    ┆ 468.0   │
│ 2024-01-29 ┆ -122.0 ┆ 346.0   │
│ 2024-01-30 ┆ 0.0    ┆ 346.0   │
│ 2024-01-31 ┆ 0.0    ┆ 346.0   │
│ 2024-02-01 ┆ -105.0 ┆ 241.0   │
└────────────┴────────┴─────────┘

### 3. 一个更复杂的策略，接受tick数据，同时合成5min和30min的k线，双周期共振的均线策略

In [51]:
# 策略逻辑
col_tick = col("t", "c", "v", "bid1", "ask1", "bid1_v", "ask1_v")
stra =  (
    col(
        col("c"),
        col("t"),
        col_tick.kline.rl5m
            .with_cols(
                col("close").stra.two_ma(10, 20).filter_cb("is_finished")
            )
            .add_suffix("m5"),
        col_tick.kline.rl30m
            .with_cols(
                col("close").stra.two_ma(10, 20).filter_cb("is_finished")
            )
            .add_suffix("m30")
    )
        .with_cols(
            col("cross_up_m30", "cross_down_m30").ffill()
        )
        .with_cols(
            col(pl.col("cross_up_m5") & pl.col("cross_up_m30")).alias("open_long_sig"),
            col(pl.col("cross_down_m5") & pl.col("cross_down_m30")).alias("open_short_sig"),
        )
        .with_cols(
            col(
                col("open_long_sig", "c").stra.exit_by_pct(0.05, False).alias("take_profit_long"),
                col("open_long_sig", "c").stra.exit_by_pct(0.02, True).alias("stop_loss_long"),
            )
                .select(
                    (pl.col("take_profit_long") | pl.col("stop_loss_long")).alias("exit_long_sig") 
                ),
            col(
                col("open_short_sig", "c").stra.exit_by_pct(0.05, True).alias("take_profit_short"),
                col("open_short_sig", "c").stra.exit_by_pct(0.02, False).alias("stop_loss_short"),
            )   
                .select(
                    (pl.col("take_profit_short") | pl.col("stop_loss_short")).alias("exit_short_sig")
                )
        )
        .with_cols(
            col("open_long_sig", "exit_long_sig", "open_short_sig", "exit_short_sig")
                .stra
                .to_hold_two_sides()
                .alias("hold")
        )
)

# tick回测逻辑
df_bt_tick = (
    qs.select(
        col(
            "bid1",
            "ask1",
            stra,
        )
            .with_cols(
                col("hold", "c", "bid1", "ask1")
                    .bt
                    .tick(qs.TradePriceType.queue, qs.MatchPriceType.simnow)
                    # .backtest_tick(qs.TradePriceType.last_price, qs.MatchPriceType.void)
            )
            .expanding()
            .over("ticker")
            .select(
                col("t", "pnl").fp.group_pnl()
            )
    )
)

In [52]:
df_bt_tick.calc_data(data_tick)

shape: (23, 3)
┌────────────┬─────┬─────────┐
│ date       ┆ pnl ┆ pnl_cum │
│ ---        ┆ --- ┆ ---     │
│ date       ┆ f64 ┆ f64     │
╞════════════╪═════╪═════════╡
│ 2024-01-06 ┆ 0.0 ┆ 0.0     │
│ 2024-01-08 ┆ 0.0 ┆ 0.0     │
│ 2024-01-09 ┆ 0.0 ┆ 0.0     │
│ 2024-01-10 ┆ 0.0 ┆ 0.0     │
│ 2024-01-11 ┆ 0.0 ┆ 0.0     │
│ …          ┆ …   ┆ …       │
│ 2024-01-27 ┆ 0.0 ┆ -119.0  │
│ 2024-01-29 ┆ 0.0 ┆ -119.0  │
│ 2024-01-30 ┆ 0.0 ┆ -119.0  │
│ 2024-01-31 ┆ 0.0 ┆ -119.0  │
│ 2024-02-01 ┆ 0.0 ┆ -119.0  │
└────────────┴─────┴─────────┘

### 4. 使用内置的策略

In [ ]:
(qs
    .with_cols(
        col("high", "low", "close").stra.c66()
    )
    .select(pl.all().qs.fp.bt(fee_rate = 0.0000)) # 只是做示例用，没有手续费
    .calc_data(data_kline)
    .qs
    ._line()
)

### 5. 内置的tick因子与内置的k线策略结合

In [54]:
(qs
    .with_cols(
        col("t", "c", "v", "bid1", "ask1", "bid1_v", "ask1_v")
            .kline
            .rl1m
            .expanding()
    )
    .with_cols(
        col("high", "low", "close")
            .stra
            .c66()
            .filter_cb("is_finished")
    )
    .with_cols(
        col("c", "v", "bid1", "ask1")
            .ta
            .order_flow_gap
            .rolling(2000)
            .with_cols(
                (pl.col("of_gap") > 100).alias("open_long_sig_of"),
                (pl.col("of_gap") < -100).alias("open_short_sig_of"),
            )
    )
    .with_cols(
        (pl.col("open_long_sig") & pl.col("open_long_sig_of")).alias("open_long_sig"),
        (pl.col("open_short_sig") & pl.col("open_short_sig_of")).alias("open_short_sig"),
    )
    .select(pl.all().qs.fp.bt(-1.0, 1.0))
    .calc_data(data_tick)
)

shape: (23, 3)
┌────────────┬────────┬─────────┐
│ date       ┆ pnl    ┆ pnl_cum │
│ ---        ┆ ---    ┆ ---     │
│ date       ┆ f64    ┆ f64     │
╞════════════╪════════╪═════════╡
│ 2024-01-06 ┆ 0.0    ┆ 0.0     │
│ 2024-01-08 ┆ 0.0    ┆ 0.0     │
│ 2024-01-09 ┆ 18.0   ┆ 18.0    │
│ 2024-01-10 ┆ 8801.0 ┆ 8819.0  │
│ 2024-01-11 ┆ 2285.0 ┆ 11104.0 │
│ …          ┆ …      ┆ …       │
│ 2024-01-27 ┆ 0.0    ┆ 39071.0 │
│ 2024-01-29 ┆ 0.0    ┆ 39071.0 │
│ 2024-01-30 ┆ -15.0  ┆ 39056.0 │
│ 2024-01-31 ┆ 0.0    ┆ 39056.0 │
│ 2024-02-01 ┆ -19.0  ┆ 39037.0 │
└────────────┴────────┴─────────┘

### 6. 自定义行计算

`qust`底层用的rust，性能有保障，但是不能也没有必要覆盖所有的情况，所以自定义算子很重要。

实现一个自定义的算子之后，这个算子就能像内置算子那样在各种上下文计算，比如`rolling`, `group_by`, `over`之类

虽然目前自定义的行算子比polars要高出很多倍（见上面的测试），但是毕竟比rust慢，所以最好是在策略的最后阶段比如仓位管理之类的时候去自定义行算子

In [55]:
# 例子1，自定义一个均线计算
class MeanUdf(qs.UdfRow):

    def __init__(self):
        # 在内部做状态保留
        self.sum = 0.0
        self.count = 0.0

    def output_schema(self, input_schema):
        return [("mean_res", pl.Float64)]
    
    # 更新数据
    # value来自于输入的每一行
    # col("a") => update(self, a_value)
    # col("a", "b") => update(self, a_value, b_value)
    def update(self, value):
        self.sum += value
        self.count += 1.0

    # 计算结果，必须要返回一个list
    def calc(self):
        return [self.sum / self.count]

    # 如果需要支持rolling，必须要实现这个方法，说明怎么滚动
    def retract(self, value):
        self.sum -= value
        self.count -= 1.0

import numpy as np
n = 1000
data_test = pl.DataFrame({
    "value": np.random.randn(n),
    "code": np.random.choice(["a", "b", "c"], size=n, replace=True),
    "window": np.random.choice([10, 5, 2], size = n, replace=True),
    "intra_day": np.random.choice([True, False], size = n, replace=True)
})

e = col("value").udf.row(MeanUdf())

# 自定义的行算子可以在各类上下文中使用
qs.with_cols(
    e.expanding().alias("expanding"),
    e.rolling(10).alias("rolling"),
    e.rolling_dynamic("window").alias("rolling_dynamic"),
    e.rolling_intra_day("intra_day", 3).alias("rolling_intraday"),
    e.expanding().alias("expanding").over("code").add_suffix("over"),
    e.rolling(10).alias("rolling").over("code").add_suffix("over"),
    e.rolling_dynamic("window").alias("rolling_dynamic").add_suffix("over"),
    e.rolling_intra_day("intra_day", 3).alias("rolling_intraday").add_suffix("over"),
).calc_data(data_test)

shape: (1_000, 12)
┌───────────┬──────┬────────┬───────────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ value     ┆ code ┆ window ┆ intra_day ┆ … ┆ expanding_o ┆ rolling_ove ┆ rolling_dyn ┆ rolling_in │
│ ---       ┆ ---  ┆ ---    ┆ ---       ┆   ┆ ver         ┆ r           ┆ amic_over   ┆ traday_ove │
│ f64       ┆ str  ┆ i64    ┆ bool      ┆   ┆ ---         ┆ ---         ┆ ---         ┆ r          │
│           ┆      ┆        ┆           ┆   ┆ f64         ┆ f64         ┆ f64         ┆ ---        │
│           ┆      ┆        ┆           ┆   ┆             ┆             ┆             ┆ f64        │
╞═══════════╪══════╪════════╪═══════════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ 0.696872  ┆ b    ┆ 10     ┆ true      ┆ … ┆ 0.696872    ┆ null        ┆ 0.696872    ┆ null       │
│ -1.939854 ┆ a    ┆ 5      ┆ false     ┆ … ┆ -1.939854   ┆ null        ┆ -0.621491   ┆ null       │
│ 0.138143  ┆ a    ┆ 10     ┆ false     ┆ … ┆ -0.900855   ┆ null        ┆ -0.36828    ┆ null       │
│ -0.767553 ┆ b    ┆ 10     ┆ false     ┆ … ┆ -0.035341   ┆ null        ┆ -0.468098   ┆ null       │
│ 1.416855  ┆ b    ┆ 10     ┆ false     ┆ … ┆ 0.448725    ┆ null        ┆ -0.091107   ┆ null       │
│ …         ┆ …    ┆ …      ┆ …         ┆ … ┆ …           ┆ …           ┆ …           ┆ …          │
│ 2.182275  ┆ b    ┆ 10     ┆ false     ┆ … ┆ -0.015211   ┆ 0.188536    ┆ -0.146151   ┆ 0.385357   │
│ -0.608805 ┆ a    ┆ 5      ┆ true      ┆ … ┆ -0.071509   ┆ 0.153087    ┆ 0.072781    ┆ -0.545003  │
│ -0.48438  ┆ c    ┆ 5      ┆ true      ┆ … ┆ 0.038567    ┆ -0.488541   ┆ 0.185705    ┆ -0.537445  │
│ 0.226195  ┆ c    ┆ 2      ┆ false     ┆ … ┆ 0.039111    ┆ -0.539205   ┆ -0.129093   ┆ -0.288997  │
│ 3.578359  ┆ a    ┆ 5      ┆ true      ┆ … ┆ -0.06114    ┆ 0.471257    ┆ 0.978729    ┆ 0.828391   │
└───────────┴──────┴────────┴───────────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

In [56]:
# 例子2，利用自定义行算子实现一个马丁策略
class MartinGillStra(qs.UdfRow):
    # 用python自定义行算子，实现一个马丁格尔策略

    # 策略的输入
    # -----
    # col(price, line_down_std2, line_down_std1, line_middle, line_up_std1, line_up_std2)

    # price: k线价格

    # line_down_std2: k线形成的最低线

    # line_down_std1: k线形成的中下线

    # line_middle: k线的中间线

    # line_up_std1: k线形成的中上线

    # line_up_std2: k线形成的最高线

    # 策略逻辑
    # ------

    # price 处于 [line_middle, line_up_std1], 目标仓位1，
    # price 处于 [line_middle, line_up_std2], 目标仓位2,
    # price 处于 [line_up_std2, inf], 目标仓位3，
    # 反过来就是 -1， -2， -3

    # 输出
    # ------
    # col(target)
    # target: 目标仓位

    def __init__(self):
        self.last_hold = 0.0

    def output_schema(self, input_schema):
        return [("hold", pl.Float64)]

    def update(self, price, down_std2, down_std1, middle, up_std1, up_std2):
        # 如果能够保证输入没有null，可以去除这个检查，性能有提升
        if price is None or down_std2 is None or down_std1 is None or middle is None or up_std1 is None or up_std2 is None:
            return None
        if price <= down_std2:
            self.last_hold = -3.0
        elif down_std2 < price <= down_std1:
            self.last_hold = -2.0
        elif down_std1 < price <= middle:
            self.last_hold = -1.0
        elif middle < price < up_std1:
            self.last_hold = 1.0
        elif up_std1 <= price < up_std2:
            self.last_hold = 2.0
        elif up_std2 <= price:
            self.last_hold = 3.0

    def calc(self):
        return [self.last_hold]

(qs
    .with_cols(
        col(
            col("close").alias("price"),
            col("close").mean().alias("middle"),
            col("close").std().alias("std"),
        )
            .rolling(20, 1)
            .select(
                col(
                    "price",
                    (pl.col("middle") - 2.0 * pl.col("std")).alias("a"),
                    (pl.col("middle") - 1.0 * pl.col("std")).alias("b"),
                    "middle",
                    (pl.col("middle") + 1.0 * pl.col("std")).alias("c"),
                    (pl.col("middle") + 2.0 * pl.col("std")).alias("d"),
                )
                    .udf
                    .row(MartinGillStra())
            )
            .expanding()
    )
    .with_cols(
        col("close", "hold")
            .bt
            .price(fee_rate=0.0002)
            .expanding()
    )
    .select(
        col("datetime", "pnl").fp.group_pnl()
    )
    .calc_data(data_kline)
    .qs
    ._line(width = 800, height = 500)
)

alt.Chart(...)

# 参数调优

`qust`中可以做可视化+交互式参数调优，只需要把原来的表达式中的固定参数换成范围参数，比如

`col("a").mean().rolling(10)` 

替换成

`col("a").mean().rolling(pms("rolling_mean", 10, 20, step = 1))`

底层会自动找到所有的范围参数

In [2]:
data_kline = pl.read_parquet("https://github.com/baiguoname/qust/blob/main/examples/data/data_kline2.parquet?raw=true") 
# 从github读取数据，速度较慢, 建议用自己的数据

In [19]:
stra = (
    col(
        "ticker",
        "close",
        "datetime",
        col("close").stra.two_ma(pms("short", 10, 60, step = 5), pms("long", 20, 60, step = 5)), # 通过算子生成信号
    )
        .with_cols(col("cross_up", "cross_down").stra.to_hold_always().alias("hold")) # 通过信号生成目标持仓
)
# 回测
df_bt = (qs
    .select(
        stra
            .with_cols(
                col("close", "hold")
                    .bt
                    # .price(fee_rate = pms("fee_rate", 0.0, 0.0002, step = 0.00001))
                    .price(fee_rate = 0.0)
            )
            .expanding()
            .over("ticker")
            .select(
                col("pnl", "fee")
                    .sum()
                    .group_by("ticker", pl.col("datetime").dt.date().alias("date"))
            )
            .with_cols(
                col("date", col("pnl").sum().expanding())
                    .ui_plot
                    .line("pnl_by_ticker")
                    .over("ticker")
            )
            .select(
                col("fee", "pnl")
                    .sum()
                    .group_by("date")
                    .select(
                        col("date", col("pnl").sum().expanding()).ui_plot.line("pnl_all"),
                    ),
                col("fee", "pnl")
                    .sum()
                    .group_by("ticker")
                    .select(
                        col("ticker", "pnl", "fee").ui_plot.bar("ticker_split_bar"),
                    ),
                col("pnl").sum(),
            )
    )
)

In [20]:
df_bt.opt_params(data_kline)

![交互式参数寻优](examples/data/view_params.gif)

In [21]:
pl.read_parquet("all_res.parquet")

shape: (99, 3)
┌───────┬──────┬─────────────┐
│ short ┆ long ┆ pnl         │
│ ---   ┆ ---  ┆ ---         │
│ u32   ┆ u32  ┆ f64         │
╞═══════╪══════╪═════════════╡
│ 10    ┆ 20   ┆ 461.836823  │
│ 10    ┆ 25   ┆ 1686.979279 │
│ 10    ┆ 30   ┆ 1157.076965 │
│ 10    ┆ 35   ┆ 1963.798737 │
│ 10    ┆ 40   ┆ 2663.83963  │
│ …     ┆ …    ┆ …           │
│ 60    ┆ 40   ┆ 717.780487  │
│ 60    ┆ 45   ┆ 640.620697  │
│ 60    ┆ 50   ┆ -43.558167  │
│ 60    ┆ 55   ┆ 620.259247  │
│ 60    ┆ 60   ┆ 0.0         │
└───────┴──────┴─────────────┘

In [16]:
# 也可以直接循环所有参数
df_bt.loop_all_params(data_kline)

shape: (99, 3)
┌───────┬──────┬─────────────┐
│ short ┆ long ┆ pnl         │
│ ---   ┆ ---  ┆ ---         │
│ u32   ┆ u32  ┆ f64         │
╞═══════╪══════╪═════════════╡
│ 10    ┆ 20   ┆ 461.836823  │
│ 10    ┆ 25   ┆ 1686.979279 │
│ 10    ┆ 30   ┆ 1157.076965 │
│ 10    ┆ 35   ┆ 1963.798737 │
│ 10    ┆ 40   ┆ 2663.83963  │
│ …     ┆ …    ┆ …           │
│ 60    ┆ 40   ┆ 717.780487  │
│ 60    ┆ 45   ┆ 640.620697  │
│ 60    ┆ 50   ┆ -43.558167  │
│ 60    ┆ 55   ┆ 620.259247  │
│ 60    ┆ 60   ┆ 0.0         │
└───────┴──────┴─────────────┘

In [24]:
# 自定义算子 也可以做参数调优
class PowUdf(qs.UdfRow):

    def __init__(self):
        # 在内部做状态保留
        self.pow = pms("pow", 0.1, 4.0, step = 0.01)
        self.s = pms("sub", 1, 10, step = 1)
        self.value = 1.0

    def output_schema(self, input_schema):
        return [("mean_res", pl.Float64)]
    
    def update(self, value):
        self.value = value

    def calc(self):
        return [self.value ** self.pow.get_f64() - self.s.get_usize()]

    def params(self):
        return [self.pow, self.s]

data = pl.DataFrame({
    "a": range(100)
})

qs.select(
    col(
        "a", 
        col("a").udf.row(PowUdf()).expanding()
    ).ui_plot.line("ggg")
).opt_params(data)

![交互式参数寻优](./examples/data/udf_params.gif)